[package]
name = "tessera-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
